# 🧮 Taller de Python: Matrices y Sistemas de Ecuaciones Lineales

**Temas:**
- Parte I: Matrices (definición, manipulación, operaciones, determinante, inversa)
- Parte II: SEL — Cramer, Matriz inversa y Gauss-Jordan utilizando SymPy

**Librería principal:** `numpy` · **Librería simbólica:** `sympy`


## 📦 Importaciones

In [ ]:
import numpy as np
import sympy as sp

---
# Parte I — Matrices


## 1) Definir una matriz de reales

Con `numpy` usamos `np.array()` pasando una **lista de listas**:  
cada lista interior representa un **renglón** (fila).

Para declarar una matriz podemos usar el comando:

```python
import numpy as np

A = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
])
```

Para imprimir la matriz podemos usar:

```python
print(A)
```

Para obtener las dimensiones de la matriz podemos usar:

```python
print(A.shape)
```

El resultado es un vector de dos datos **(número de renglones, número de columnas)**.

Si queremos de manera independiente obtener el número de renglones o de columnas hacemos:

```python
print(A.shape[0])  # número de renglones
print(A.shape[1])  # número de columnas
```


In [ ]:
A = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
])
print(A)
print(A.shape)
print(A.shape[0])  # número de renglones
print(A.shape[1])  # número de columnas

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
(3, 3)
3
3


**Ejercicio**:

Declarar una matriz de tamaño $2 \times 4$ con su fecha de nacimiento, poniendo el dia y mes en el primer renglón y el año en el segundo renglón.

Obtener la dimensión, el número de renglones y el número de columnas

In [ ]:
A=np.array([[0, 1, 1, 1], [2 ,0 ,0 ,0]])
print(A)
print(A.shape)

[[0 1 1 1]
 [2 0 0 0]]
(2, 4)


También podemos crear matrices especiales con los siguientes comandos:

- `np.zeros((4, 3))`   
- `np.ones((4, 3))`   
- `np.eye(4)`  
- `np.eye(5, 6)`  

In [ ]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

## 2) Manipular un elemento, una columna y un renglón

> ⚠️ Python usa **índice base 0**: el primer renglón es el renglón 0.

Podemos imprimir, asignar o modificar un elemento específico de una matriz `A` con la notación `A[i, j]`.

- Podemos manipular un **renglón** completo usando `A[i, :]`
- Podemos manipular una **columna** completa usando `A[:, j]`

**Ejercicio**

- Definir una matriz `A` de tamaño 4×5 con números reales cualesquiera
- Extraer el elemento del renglón 2 y columna 3
- Sustituir toda la columna 3 por 1
- Sumar 4 a todo el renglón 2

In [ ]:

A=np.array([[1,2,3,4,5], [6,7,8,9,10], [5,4,3,2,1], [0,9,8,7,6]])
print(A)

print(A[1,2])
A[:,2]=1
print(A)
A[1,:] +=4
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 5  4  3  2  1]
 [ 0  9  8  7  6]]
8
[[ 1  2  1  4  5]
 [ 6  7  1  9 10]
 [ 5  4  1  2  1]
 [ 0  9  1  7  6]]
[[ 1  2  1  4  5]
 [10 11  5 13 14]
 [ 5  4  1  2  1]
 [ 0  9  1  7  6]]


## 3) Suma, multiplicación por escalar y producto de matrices

Vamos a definir dos matrices

$$A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} \qquad B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}$$

y realizar las siguientes operaciones. Ejecuta la celda y observa cada resultado. ¿Qué hace cada operación?

- `A + B` →
- `3 * A` →
- `A * B` →
- `A @ B` →
- `np.dot(A, B)` →
- `np.matmul(A, B)` →
- `np.prod(A)` →

> 📝 **Nota:** Para copiar una matriz `A` en una nueva matriz independiente, usaremos `A_copia = A.copy()`. Si hacemos simplemente `A_copia = A`, ambas variables apuntan a la **misma matriz en memoria**, por lo que modificar una afecta a la otra.

In [ ]:
A=np.array([[1,2], [3,4]])
B=np.array([[5,6], [7,8]])
print(A,"\n\n",B)

print("\n",A+B)
print("\n",3*A)
print("\n",A*B)
print("\n",A@B)

[[1 2]
 [3 4]] 

 [[5 6]
 [7 8]]

 [[ 6  8]
 [10 12]]

 [[ 3  6]
 [ 9 12]]

 [[ 5 12]
 [21 32]]

 [[19 22]
 [43 50]]


**Ejercicio:** Dadas las matrices

$$A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \\ 10 & 11 & 12 \end{pmatrix} \qquad B = \begin{pmatrix} 2 & 0 & 1 \\ 3 & 1 & 0 \\ 1 & 2 & 3 \\ 0 & 1 & 2 \end{pmatrix} \qquad C = \begin{pmatrix} 1 & 2 & 3 & 4 & 5 \\ 6 & 7 & 8 & 9 & 10 \\ 11 & 12 & 13 & 14 & 15 \end{pmatrix}$$

Escribir un código que realice las siguientes operaciones sin usar las funciones integradas de NumPy:

- Suma de matrices: $A + B$
- Multiplicación por escalar: $3 \cdot A$
- Producto elemento a elemento: $A \ast B$
- Producto matricial: $A \cdot C$

In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9], [10, 11, 12]])
B=np.array([[2,0,1],[3,1,0],[1,2,3], [0, 1, 2]])
C=np.array([[1,2,3, 4, 5],[6,7,8, 9, 10],[11,12,13, 14, 15]])
print(A, "\n\n", B, "\n\n", C)

SUMA=np.zeros((4,3))
print("\n",SUMA)

for i in range(A.shape[0]):
  for j in range(A.shape[1]):
    SUMA[i,j]=A[i,j]+B[i,j]

print("\n",SUMA)

MultEsc=np.zeros((4,3))
print("\n",MultEsc)

for i in range(A.shape[0]):
  for j in range(A.shape[1]):
    MultEsc[i,j]=3*A[i,j]

print("\n",MultEsc)

ProdMat=np.zeros((4,5))

for i in range(A.shape[0]):
  for j in range(C.shape[1]):
    for k in range(A.shape[1]):
      ProdMat[i,j] += A[i,k]*C[k,j]

print("\n",ProdMat)
print("\n",A @ C)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

 [[2 0 1]
 [3 1 0]
 [1 2 3]
 [0 1 2]] 

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[ 3.  2.  4.]
 [ 7.  6.  6.]
 [ 8. 10. 12.]
 [10. 12. 14.]]

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]
 [30. 33. 36.]]

 [[ 46.  52.  58.  64.  70.]
 [100. 115. 130. 145. 160.]
 [154. 178. 202. 226. 250.]
 [208. 241. 274. 307. 340.]]

 [[ 46  52  58  64  70]
 [100 115 130 145 160]
 [154 178 202 226 250]
 [208 241 274 307 340]]


## 4) Calcular el determinante

Usamos `np.linalg.det()`.  
Si **det(A) ≠ 0**, la matriz es invertible.

**Aplicación**: Definir una matriz cuadrada y calcular su determinante.


In [ ]:
A=np.array([[1,2,3], [4,5,6],[5,7,9]])
print(A, "\n")
round(np.linalg.det(A), 10)

[[1 2 3]
 [4 5 6]
 [5 7 9]] 



np.float64(0.0)

**Ejercicio**: Utilizar el método de Cramer para obtener la solución del sistema de ecuaciones lineales $Ax = b$:

$$\begin{cases} 2x_1 + x_2 - x_3 + 3x_4 = 7 \\ x_1 + 3x_2 + 2x_3 - x_4 = 5 \\ 3x_1 - x_2 + x_3 + 2x_4 = 4 \\ x_1 + 2x_2 - 3x_3 + x_4 = 3 \end{cases}$$


In [ ]:
A=np.array([[2,1,-1,3], [1,3,2,-1], [3, -1,1,2],[1,2,-3,1] ])
B=np.array([[7], [5],[4],[3]])

print(A, "\n", B)

A_1 = A.copy()
A_1[:,0]=B[:,0]
print("\n", A_1)
Det=np.linalg.det(A)
Det1=np.linalg.det(A_1)
x1=Det1/Det

print(Det, Det1, x1)


A_2 = A.copy()
A_2[:,1]=B[:,0]
print("\n", A_2)
Det2=np.linalg.det(A_2)
x2=Det2/Det

print(x2)

[[ 2  1 -1  3]
 [ 1  3  2 -1]
 [ 3 -1  1  2]
 [ 1  2 -3  1]] 
 [[7]
 [5]
 [4]
 [3]]

 [[ 7  1 -1  3]
 [ 5  3  2 -1]
 [ 4 -1  1  2]
 [ 3  2 -3  1]]
-75.00000000000004 -30.000000000000014 0.39999999999999997

 [[ 2  7 -1  3]
 [ 1  5  2 -1]
 [ 3  4  1  2]
 [ 1  3 -3  1]]
1.6000000000000003


## 5) Calcular la matriz inversa

Usamos `np.linalg.inv()`.  
Verificamos que **A · A⁻¹ = I**.

**Aplicación**: Definir una matriz cuadrada y calcular su inversa. Comprobar que A · A⁻¹ = I.



In [ ]:
A=np.array([[2,1,-1,3], [1,3,2,-1], [3, -1,1,2],[1,2,-3,1] ])
B=np.array([[7], [5],[4],[3]])

Ainv=np.linalg.inv(A)

print(np.round(Ainv, 3))

print(np.round(Ainv @ A, 4))

print("Solucion:", Ainv @ B)

[[-0.4    0.067  0.467  0.333]
 [ 0.2    0.2   -0.2    0.   ]
 [ 0.2    0.133 -0.067 -0.333]
 [ 0.6   -0.067 -0.267 -0.333]]
[[ 1. -0. -0. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
Solucion: [[0.4]
 [1.6]
 [0.8]
 [1.8]]


**Ejercicio**: Resolver el SEL anterior con el método de matriz inversa.

---
# Parte II — Sistemas de Ecuaciones Lineales (SEL)

Un SEL se escribe en forma matricial como **Ax = b**:

$$
\begin{pmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{pmatrix}
\begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix}
=
\begin{pmatrix} b_1 \\ b_2 \\ b_3 \end{pmatrix}
$$

Usaremos el mismo sistema en los tres métodos para comparar:

$$
\begin{cases}
2x - y + z = 8 \\
-3x - y + 2z = -11 \\
-2x + y + 2z = -3
\end{cases}
$$


##  Resolución con SymPy

SymPy trabaja con **aritmética exacta** (fracciones, radicales).  
Usamos `sp.Matrix` y el método `.solve()` de la matriz aumentada,
o directamente `sp.linsolve`.


In [ ]:
# Definir el sistema con SymPy (valores exactos)
A_sp = sp.Matrix([[ 2, -1,  1],
                  [-3, -1,  2],
                  [-2,  1,  2]])

b_sp = sp.Matrix([8, -11, -3])

# --- Método 1: resolver con la inversa simbólica ---
x_sympy = A_sp.inv() * b_sp
print("Solución con A⁻¹ · b (SymPy):")
sp.pprint(x_sympy)


Solución con A⁻¹ · b (SymPy):
⎡62 ⎤
⎢── ⎥
⎢15 ⎥
⎢   ⎥
⎢29 ⎥
⎢── ⎥
⎢15 ⎥
⎢   ⎥
⎣5/3⎦


In [ ]:
# --- Método 2: linsolve (más general, acepta sistemas sub/sobre-determinados) ---
x1, x2, x3 = sp.symbols('x1 x2 x3')

sol = sp.linsolve((A_sp, b_sp), x1, x2, x3)
print("Solución con sp.linsolve:")
sp.pprint(sol)


Solución con sp.linsolve:
⎧⎛62  29     ⎞⎫
⎨⎜──, ──, 5/3⎟⎬
⎩⎝15  15     ⎠⎭


In [ ]:
# --- Método 3: forma escalonada reducida (RREF) ---
M_aug = A_sp.row_join(b_sp)   # matriz aumentada simbólica
rref, pivots = M_aug.rref()

print("Forma escalonada reducida (RREF) de [A|b]:")
sp.pprint(rref)
print("\nColumnas pivote:", pivots)
print("\nSolución (última columna de la RREF):", rref[:, -1].T)


Forma escalonada reducida (RREF) de [A|b]:
⎡         62 ⎤
⎢1  0  0  ── ⎥
⎢         15 ⎥
⎢            ⎥
⎢         29 ⎥
⎢0  1  0  ── ⎥
⎢         15 ⎥
⎢            ⎥
⎣0  0  1  5/3⎦

Columnas pivote: (0, 1, 2)

Solución (última columna de la RREF): Matrix([[62/15, 29/15, 5/3]])


## Ejercicio

Resolver el siguiente sistema de ecuaciones lineales:

$$\begin{cases} x_1 + 2x_2 + 3x_3 = 6 \\ 2x_1 + 4x_2 + 6x_3 = 12 \\ x_1 - x_2 + x_3 = 2 \end{cases}$$



In [ ]:
A_sp = sp.Matrix([[ 1, 2,  3],
                  [2, 4,  6],
                  [1,  -1,  1]])

b_sp = sp.Matrix([6, 12, 2])

# --- Método 1: resolver con la inversa simbólica ---
x_sympy = A_sp.inv() * b_sp
print("Solución con A⁻¹ · b (SymPy):")
sp.pprint(x_sympy)

NonInvertibleMatrixError: Matrix det == 0; not invertible.

In [ ]:
x1, x2, x3 = sp.symbols('x1 x2 x3')

sol = sp.linsolve((A_sp, b_sp), x1, x2, x3)
print("Solución con sp.linsolve:")
sp.pprint(sol)

Solución con sp.linsolve:
⎧⎛10   5⋅x₃  4   2⋅x₃    ⎞⎫
⎨⎜── - ────, ─ - ────, x₃⎟⎬
⎩⎝3     3    3    3      ⎠⎭


In [ ]:
M_aug = A_sp.row_join(b_sp)   # matriz aumentada simbólica
rref, pivots = M_aug.rref()

print("Forma escalonada reducida (RREF) de [A|b]:")
sp.pprint(rref)
print("\nColumnas pivote:", pivots)


Forma escalonada reducida (RREF) de [A|b]:
⎡1  0  5/3  10/3⎤
⎢               ⎥
⎢0  1  2/3  4/3 ⎥
⎢               ⎥
⎣0  0   0    0  ⎦

Columnas pivote: (0, 1)


## Ejercicio: Balanceo de reacciones químicas

El balanceo de una reacción química puede formularse como un sistema de ecuaciones lineales, donde cada elemento impone una ecuación de conservación.

Para cada una de las siguientes reacciones, encontrar los coeficientes estequiométricos:

a) Reacción entre las especies $Fe^{3+}$, $Sn^{2+}$, $Fe^{2+}$ y $Sn^{4+}$

b) Reacción entre las especies $MnO_4^-$, $H^+$, $Fe^{2+}$, $Mn^{2+}$, $Fe^{3+}$ y $H_2O$

- x1 -> Fe3+
- x2 -> Sn2+
- x3 -> Fe2+
- x4 -> Sn4+

- x1+x3=0
- x2 + x4=0
- 3x1 + 2x2 + 2x3 + 4x4 =0


Fijamos x4=1
Nos da x1=-2 ; x2=-1 ; x3=2



In [ ]:
A_sp = sp.Matrix([[ 1, 0,  1,0],
                  [0, 1,  0, 1],
                  [3,  2,  2, 4]])

b_sp = sp.Matrix([0, 0, 0])

M_aug = A_sp.row_join(b_sp)   # matriz aumentada simbólica
rref, pivots = M_aug.rref()

print("Forma escalonada reducida (RREF) de [A|b]:")
sp.pprint(rref)
print("\nColumnas pivote:", pivots)

Forma escalonada reducida (RREF) de [A|b]:
⎡1  0  0  2   0⎤
⎢              ⎥
⎢0  1  0  1   0⎥
⎢              ⎥
⎣0  0  1  -2  0⎦

Columnas pivote: (0, 1, 2)
